apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: openldap-build-deploy
spec:
  workspaces: 
  - name: repo-credentials
    description: Secret with docker credentials for image repository (config.json key)
  - name: git-source
    description: Git repo with the source code
  params:
  - name: gitUrl
    description: Git repo url
  - name: revision
    description: The revision to fetch
    default: "master"
  tasks:
  # Clone the project repository containing all the software
  - name: clone-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: git-source
    params:
    - name: url
      value: "$(params.gitUrl)"
    - name: revision
      value: "$(params.revision)"
    - name: deleteExisting
      value: "true"
  # Build image
  - name: build-image
    taskRef:
      name: kaniko
    runAfter:
    - clone-repo
    workspaces:
    - name: source
      workspace: git-source
    - name: dockerconfig
      workspace: repo-credentials
    params:
    - name: CONTEXT
      value: docker
    - name: IMAGE
      value: harbor.jativa:443/francisco/openldap:0.1
    - name: DOCKERFILE
      value: docker/dockerfile
    # This is necesary because Kaniko has not the CA certificate used by harbor
    - name: EXTRA_ARGS
      value:
      - --skip-tls-verify
