apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tests
  labels:
spec:
  description: >-
    Task to execute the robot tests specified in the "test" directory of the resource
  params:
  workspaces:
  - name: source
  steps:
  - name: test
    image: python:3.9.7-bullseye
    workingDir: $(workspaces.source.path)
    script: |
      apt update
      # pip install --upgrade pip
      python3 -m pip install --ignore-installed haikunator requests pyvcloud progressbar pathlib robotframework robotframework-seleniumlibrary robotframework-requests robotframework-SSHLibrary
      apt install -y ldap-utils
      apt install -y 389-ds-base
      cd tests
      robot -d output ldap.robot 
