apiVersion: v1
kind: Service
metadata:
  name: openldap-sample
spec:
  selector:
    openldap: sample
  ports:
    - protocol: TCP
      port: 389 
      targetPort: 389
  type: LoadBalancer
  loadBalancerIP: 192.168.122.210
